### PR TITLE
Fix qt project for creating library

### PR DESCRIPTION
**Pull request by lighta**
Need to add template to create the library properly.
Otherwise will try to create an executable and get link error.
```
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/10/../../../../lib64/crt1.o: in function `_start':
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status
```

### CODE REVIEW

**Comment by wuarmin** [comment]
Makes sense. Thank you for the PR.

**Comment by lighta** [comment]
Wait a second actually, this break your test, I'll fix everything in a bit

**Comment by lighta** [comment]
See https://github.com/lighta/QtConnectionPool.
I'll do a new PR for this but basically mine is aiming for oracle so I took few shortcut in fixing test.

Basically I introduced `waitTimeoutInMs` in getConnection(), cause this is typically what you'll do in a threadPool usage, unless you want client class to do pooling, which is not ideal.
I also completly change the `ConnectionPoolPrivate::checkConnectionPool()`, I did not understand that max check since you shouldn't have created con > max in first case.
What I did was introduce `inactivityPeriod`, and when ```connection.lastUse > inactivityPeriod``` then we realease it. that all.

If you put a library you also need to use namespace else you increase collision symbole chance.
Finally I didn't finish yet, but if you do private implementation pattern, you shouldn't have the include of the private in interface. (well fine you could but it's bad practice).
NB : Consider using RAII pattern to handle exception path for thing like mutex.

**Comment by wuarmin** [comment]
@lighta Your inputs are great :+1: . Your changes, especially, around `getConnection` make totally sense. 
QtConnectionPool arose out of a meaningful leisure activity two years ago. It worked 100% well for my private, and comparative simple use-cases.

I am glad that you take the time to improve and fix the weaknesses and the project can evolve. Please do a new PR.

P.S. please point me to the code, where privates are included in the interface. Do you mean `DatabaseConnection`, which you have removed? 

Best regards

**Pull request merged**
