### PR TITLE
Revamped

### PR DESCRIPTION
**Pull request by lighta**
- qmake project reorganize to create the library and the test executable.
- Usage of QSharedPointer, instead custom unsafe sharedPtr.
- Add timeout option to ConnectionPool::getConnection()
- Add PoolConfig.inactivityPeriod : time before release unused connection. (to reduce Pool usage, only if > minConnection)
- Revamp ConnectionPoolPrivate::checkConnectionPool. to act like a curator thread. (remove the unused connection and refresh the one that are connection for too long).
- Remove unused file
- Add extra tests in connectionPoolTest.
-

### CODE REVIEW

**Comment by wuarmin** [comment]
@lighta I looked through code and tested the `qtconnectionpool` in my apps (PostgreSql). It looks great!
Many thanks for your work! :boom:

one little thing: 
I have some issues with test-file-paths. 
Please let me know, how you run the test-suite (main.pro). I had to change the test-config-filepaths to run the test-suite properly.

thanks

**Comment by wuarmin** [comment]
@lighta I looked through the code and tested the `qtconnectionpool` in my apps (PostgreSql). It looks great!
Many thanks for your work! :boom:

**One little thing:** 
I have some issues with test-file-paths. 
Please let me know, how you run the test-suite (main.pro). I had to change the test-config-filepaths to run the test-suite properly.

```txt
qmake Test.pro
make
cd ../bin
```
```txt
LD_LIBRARY_PATH=./ ./qtconnectionpool_tests
```
```txt
********* Start testing of PoolConfigTest *********
Config: Using QtTest library 5.13.0, Qt 5.13.0 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 5.3.1 20160406 (Red Hat 5.3.1-6))
PASS   : PoolConfigTest::initTestCase()
0x7feb1b3dac80 : PoolConfig: Config file '/home/user/c/QtConnectionPool/bin/etc/individual_config.json' cannot be opened
FAIL!  : PoolConfigTest::testIndividualValues() Compared values are not the same
   Actual   (poolConfig.checkInterval): 10000
   Expected (30000)                   : 30000
   Loc: [database/poolconfigtest.cpp(37)]
0x7feb1b3dac80 : PoolConfig: Config file '/home/user/c/QtConnectionPool/bin/etc/empty_config.json' cannot be opened
PASS   : PoolConfigTest::testDefaultValues()
PASS   : PoolConfigTest::cleanupTestCase()
Totals: 3 passed, 1 failed, 0 skipped, 0 blacklisted, 1ms
********* Finished testing of PoolConfigTest *********
```
thanks

**Comment by wuarmin** [comment]
@lighta I fixed the file-path-issue by using the Qt Resource System.

**Comment by lighta** [comment]
Great I'm not that familiar to QT to be a greater help. I don't have the editor neither so it was a bit longer =(
Glad that you like it.
It's first implementation tought, I'm not quite satisfied yet but I'll you know.
The `ConnectionPoolPrivate` singleton requirement is only due to the unborrow system, which is soso. A custom object with member {Connection,ConnectionPool} and having in his destructor putting back the connection to ConnectionPool would probably safer and remove that constraint... ( I sadly have not much time to allocate for such yet).
Thinking about it that customObj is somewhat a bit what you had with `unused()` concept.

**Comment by wuarmin** [comment]
All right! Qt Resource System is just a mechanism for storing binary files in the executable.

I'm happy about your input and the effort you put into the changes. Thank you!

> It's first implementation tought, I'm not quite satisfied yet but I'll you know.
> The ConnectionPoolPrivate singleton requirement is only due to the unborrow system, which is soso.

You mean this code, aren't you?
https://github.com/wuarmin/QtConnectionPool/blob/a3f2afbb31dda3d6e2d301b9feab8b537e7ae939/QtConnectionPool/database/connectionpoolprivate.cpp#L16

>A custom object with member {Connection,ConnectionPool} and having in his destructor putting back the connection to ConnectionPool would probably safer and remove that constraint... ( I sadly have not much time to allocate for such yet).
> Thinking about it that customObj is somewhat a bit what you had with unused() concept.

Ok, how would you name this customObj? Maybe BorrowedConnection? So this should be a proxy object for the connection, with the addition that it handles the unborrowing (explicit and implicit)?

`ConnectionPool::getConnection` would return a `QSharedPointer<BorrowedConnection>`.

With that changes, we could get rid of `ConnectionPoolPrivate::getInstance()` and the `unBorrowDeleteHandler`.

**Pull request merged**
